name: flutter_bank
description: A simple banking application using Flutter

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Application version information
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # For parsing date strings and formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# Flutter configuration
flutter:
  # Enable material design
  uses-material-design: true

  # Include application assets
  assets:
    - assets/data/
    - assets/images/
